-- Tabla para seguir hashtags
CREATE TABLE IF NOT EXISTS hashtag_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  hashtag TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, hashtag)
);

-- Políticas de seguridad (RLS)
ALTER TABLE hashtag_follows ENABLE ROW LEVEL SECURITY;

-- Permitir a los usuarios ver sus propios follows
CREATE POLICY "Users can view their own hashtag follows" 
ON hashtag_follows FOR SELECT 
USING (auth.uid() = user_id);

-- Permitir a los usuarios seguir hashtags
CREATE POLICY "Users can insert their own hashtag follows" 
ON hashtag_follows FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Permitir a los usuarios dejar de seguir hashtags
CREATE POLICY "Users can delete their own hashtag follows" 
ON hashtag_follows FOR DELETE 
USING (auth.uid() = user_id);
